Feature/diagram
Benawi/database-based-diagram pull request #1
Opened 2023-07-25 19:53 UTC by Benawi

## [Implemented Features](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/database_from_diagram.md)
### General requirements
- [x] Make sure that you used the correct Gitflow.
- [x] Make sure that you document your work in a professional way.
### Project requirements
- [x] Create a file named schema_based_on_diagram.sql where you implement the database from the diagram.
- [x] Join tables from many-to-many relationships might not appear in the diagram, but you still need them.
- [x] Add the FK indexes.
![image](https://github.com/Benawi/database-based-diagram/assets/21217148/89d609f1-2986-47c5-8d57-d95b248e6536)

2023-07-25 21:28 UTC, tugsem requested changes
##  STATUS: REQUIRED CHANGES ♻️
Hello @Benawi and @wolterbwambale 👋 , 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

![ Alt Text](https://media.giphy.com/media/l0MYC5rnAHehkVKRq/giphy.gif)
## Highlights 🚀 
✔️all tables created except the join table
✔️all ids are set as primary keys
✔️indexes created for foreign keys except for the join table
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a on
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-25 21:28 UTC, tugsem commented on schema_based_on_diagram.sql
> +    treatment_id INTEGER REFERENCES treatments(id)
- [ ] Please create a join table for many to many relationships such as here as per the requirement.

2023-07-25 21:28 UTC, tugsem commented on schema_based_on_diagram.sql
> +CREATE INDEX id_medical_histories_treatments_id ON medical_histories (treatment_id);
- [ ] Please add indexes for all foreign keys you are going to set up for the join table as per the requirement. This would boost the execution time of your queries.

2023-07-26 17:23 UTC, Benawi commented
### Changes ♻️
- [x] Add indexes for all foreign keys 
- [x] Create a join table for many to many relationships

2023-07-26 17:43 UTC, sumairq approved these changes
### Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-26 19:51 UTC, merged